### ISSUE TITLE
TODO: Disk Allocation logic.

### ISSUE THREAD

**Issue by romanrizzi** [DavidCorrea/UNQ-SO-2014#2]
I just introduced the logic of the HDD and a File System for it. Each Disk Block cell inside a File equals to a Block. We need to implement this requeriments in order to finish our work

R.

**Comment by DavidCorrea** [comment]
Ok, so we're almost done. Great news! We have this left and the algorithm
for the memory, right? Or it's done too? We're almost there. I should be
"free" for tomorrow after the exam. Will check it by then and give my
p.o.v. about it.

Cheers, David C.

_They told me I was a machine._
